### PR TITLE
Update gimp-normalmap-1.2.2-r1.ebuild

### PR DESCRIPTION
**Pull request by AzP**
Add -lm to libraries (tried adding it to LDFLAGS, but it missed it for some
reason when doing -Wl,--as-needed) so it compiles properly. Also update
ChangeLog.

### CODE REVIEW

**Comment by AzP** [comment]
And we'll use this one instead. That works, right?

**Comment by hasufell** [comment]
!!! Reason: Failed on SHA256 verification
!!! Got: ed1a58cf736f4b1ae94a1db3c71a5ed3d808037f94e8f798d926f84d4097169a
!!! Expected: 9e15f85e6a1cc32ae6d43979e93f0ead9f4c8152f6fa6a786aaac34a7869b28c
- Digest verification failed:
- /home/jule/git/sunrise/media-plugins/gimp-normalmap/gimp-normalmap-1.2.2-r1.ebuild
- Reason: Failed on SHA256 verification
- Got: ed1a58cf736f4b1ae94a1db3c71a5ed3d808037f94e8f798d926f84d4097169a
- Expected: 9e15f85e6a1cc32ae6d43979e93f0ead9f4c8152f6fa6a786aaac34a7869b28c

**Comment by hasufell** [comment]
Did you use "sunrise-commit"? If you do, then such things should not happen.

**Comment by hasufell** [comment]
if you do not use sunrise-commit, then you need to do this:
- modify the ebuild
  (if you add any NEW file, then you need to run: git add <NEWFILE>)
- run: echangelog "I did this and that"
- run: repoman full
- run: git commit -a -m "I did this and that"
- run: git push <remote> <branch>
- log into github, create pull request

sunrise-commit should do most of those steps for you except the last one, so when you are not familiar with git, use "sunrise-commit"

also see: http://overlays.gentoo.org/proj/sunrise/wiki/HowToCommit (not all steps apply from that link, only look at the sections "Add the Ebuild" and "Generate ChangeLog and Manifest and Check for QA Problems" for now)

**Comment by hasufell** [comment]
I fixed that for you... try to play with your overlay a bit so you get it right next time.

**Comment by AzP** [comment]
Yes, I will, thank you!

I did that pull request before I got home to setup a new overlay. I did
that from my windows machine at work, so I didn't have any possibility to
check the Manifest. Thank you for your help and support, I'll get it right
the next time! Then I'll go for a real local repository, plus use
sunrise-commit.

2013/9/24 Julian Ospald notifications@github.com

**Pull request merged**
