### PR TITLE
New Glib fix pull request

### PR DESCRIPTION
**Pull request by dragynbane222**
New pull request to include all files needed, glib patch included and updated manifest and ebuild that was included before.

### CODE REVIEW

**Comment by hasufell** [comment]
You have a typo in the patch name causing failure.

**Comment by hasufell** [comment]
Changelog entries are missing. Either use "echangelog <message>" manually or use sunrise-commit as described in the howtocommit guide.

http://overlays.gentoo.org/proj/sunrise/wiki/HowToCommit

**Comment by hasufell** [comment]
Any news here?

**Comment by hasufell** [comment]
hello

**Comment by dragynbane222** [comment]
sorry, had a lot of homework come up (college, man,) and as such could not sustain what I was doing, gonna be getting Gentoo back up and try and work on this this next weekend.

**Comment by hasufell** [comment]
also check https://github.com/gentoo-sunrise/sunrise/wiki

**Pull request closed without merging**
