### PR TITLE
update to net-im/spark-2.6.3, fix doicon call

### PR DESCRIPTION
**Pull request by lkraav**

### CODE REVIEW

**Comment by hasufell** [comment]
You can improve it even more. doicon now supports "-s <size>" which will install into /usr/share/icons/hicolor/<size>/apps
Then you need to run the helpers from gnome2-utils to update the icon cache (kde does that on it's own), see the gnome2_\* calls in x11-misc/spacefm.

**Comment by hasufell** [comment]
any progress here?

**Comment by lkraav** [comment]
Really haven't had any further time...

**Comment by hasufell** [comment]
If you don't work harder, @mgorny will install systemd on your computer.

**Comment by lkraav** [comment]
rotfl +1000

**Comment by hasufell** [comment]
@mgorny please go on and install systemd

**Comment by hasufell** [comment]
last ping before I will close this pull request

**Comment by hasufell** [comment]
create a new pull request with the fixes I mentioned

**Pull request closed without merging**
