### PR TITLE
Update gimp-normalmap-1.2.2-r1.ebuild

### PR DESCRIPTION
**Pull request by AzP**
Add -lm to libraries (tried adding it to LDFLAGS, but it missed it for some reason when doing -Wl,--as-needed) so it compiles properly.

### CODE REVIEW

**Comment by hasufell** [comment]
The Manifest has not been updated and the changelog entry is missing.

**Comment by AzP** [comment]
Oh, I didn't know I should add them. There, can you see that? It's my first pull request, so I'm kind of oblivious :)

**Comment by hasufell** [comment]
The manifest says gimp-normalmap-1.2.2-r2.ebuild, but there is none.

**Comment by AzP** [comment]
Oh, I'm sorry.. I changed the name of the ebuild on my local overlay, but added the changes manually on the website to the existing ebuild file on github. Should I rename the ebuild file to the new version?

**Comment by AzP** [comment]
Now I renamed it to the new version. Thank you for your feedback!

**Comment by hasufell** [comment]
you walked right into the trap :P 
You only do revision bumps when there are new features or the installed files change. This is just a build-time fix, so we do not need a revision bump. Rename it to -r1

**Comment by AzP** [comment]
Aha, ok. Good to know in the future! But how will portage now that the package has been updated to build correctly if the -r# isn't updated?
I'm not home right now, but I'll recreate the manifest file when I get home after work this evening!

**Comment by hasufell** [comment]
Portage does not need to know. The guy who had build time issues could not have it installed anyway... so he will wait for the next sync and try again. If you push to -r2, then everyone (even those who had no build-time issues) have to rebuild.

**Comment by AzP** [comment]
Good point, I thought about that as well.

**Comment by AzP** [comment]
There we go, now it should be correct. _crosses fingers_

**Comment by hasufell** [comment]
Manifest is still broken for me.

Use "repoman full" to check for ebuild errors and "repoman manifest" to create the manifest.

**Comment by AzP** [comment]
Well I'll be damned, you're right. I didn't know of repoman, great tool! Thank you for that tip.

**Comment by AzP** [comment]
I hope that's better.

**Comment by hasufell** [comment]
Hmm, now look at this... we have 9 commits. Are you familiar enough with git to redo this pull request so that it shows one commit? E.g. you do a "soft" reset in your local repo, commit it and then do a non-fast-forward push.

**Comment by AzP** [comment]
I think one of my problems is that I never checked out a local branch, I just forked in the Web UI and edited the files directly in there. I'm trying to figure out how to do the soft reset though.

**Comment by hasufell** [comment]
hehe... now we have 11 commits :D

**Comment by AzP** [comment]
Noooooo! I created a new branch from the point prior to my first commit.
Then I did a squash of all my 9 commits into one, and then commited that to
that branch...
Can I "unpull" my request?

2013/9/24 Julian Ospald notifications@github.com

**Comment by AzP** [comment]
I'll try to undo this one.

**Comment by hasufell** [comment]
Advise... since you are new to git, don't play with the reset and non-fast-forward thing. Make sure your local overlay you have checked out is safe and don't delete it.
Then fork sunrise for a second time and copy over the work of your old repo. Then do ONE commit with the tool "sunrise-commit" from app-portage/overlay-utils.

this way:
`sunrise-commit -c "[media-plugins/gimp-normalmap] fix linking error"`

**Comment by AzP** [comment]
Good tip, thank you. But wasn't the other pull request correct? The one from my branch I created?

**Pull request closed without merging**
